export const translations = {
  ru: {
    profile: 'Мои Посты',
    admin: 'Панель Администратора',
    logout: 'Выйти',
    search: 'Поиск',
    tags: 'Тэги',
    signIn: 'Войти',
    signUp: 'Зарегистрироваться',
    signInTitle: 'Вход в аккаунт',
    signUpTitle: 'Создание аккаунта',
    password: 'Пароль',
    fullName: 'Полное имя',
    comments: 'Комментарии',
    commentsLabel: 'Написать комментарий',
    commentsBtn: 'Отправить',
    write: 'Написать статью',
    delete: 'Удалить статью',
    deleteMultiple: 'Удалить выбранные статьи',
    noRows: 'У вас нет созданных постов',
    authorRating: 'Рейтинг Автора',
    title: 'Заголовок',
    links: 'Ссылка на пост',
    edit: 'Изменить пост',
    ratingTitle: 'Рейтинг',
    tagsEmpty: 'Еще нет созданных тэгов',
    deleteUser: 'Удалить пользователя',
    deleteUsers: 'Удалить выбранных пользователей',
    status: 'Статус',
    usersProfile: 'Профиль пользователей',
    goToProfile: 'Личный Кабинет',
    rate: 'Оценить',
    nameOfArt: 'Произведение: ',
    more: 'Подробнее',
    likes: 'Лайки',
    settings: 'Настройки профиля',
    rateReview: 'Оцените обзор',
    download: 'Загрузить Постер',
    genres: 'Жанр',
    typeText: 'Введите текст...',
    games: 'Игры',
    cinema: 'Кино',
    books: 'Книги',
    post: "Опубликовать",
    cancel: 'Отмена',
    save: 'Сохранить',
    setStatusAdmin: 'Выдать статус Админа',
    setStatusUser: 'Выдать статус Юзера',
  },
  en: {
    profile: 'My Posts',
    admin: 'Admin Panel',
    logout: 'Sign Out',
    search: 'Search',
    tags: 'Tags',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signInTitle: 'Login',
    signUpTitle: 'Create An Account',
    password: 'Password',
    fullName: 'Full Name',
    comments: 'Comments',
    commentsLabel: 'Write comments',
    commentsBtn: 'Send',
    write: 'Write a Review',
    delete: 'Delete Review',
    deleteMultiple: 'Delete Selected Reviews',
    noRows: 'You have no posts created',
    authorRating: 'Rating of Author',
    title: 'Title',
    links: 'Post link',
    edit: 'Edit Post',
    ratingTitle: 'Rating',
    tagsEmpty: 'No tags created yet',
    deleteUser: 'Delete user',
    deleteUsers: 'Delete selected users',
    status: 'Status',
    usersProfile: 'Users Profile',
    goToProfile: 'Go To Profile',
    rate: 'Rate',
    nameOfArt: 'Name of Art: ',
    more: 'More',
    likes: 'Likes',
    settings: 'Settings Profile',
    rateReview: 'Rate the Review',
    download: 'Download Poster',
    genres: 'Genres',
    typeText: 'Type a Text...',
    games: 'Games',
    cinema: 'Cinema',
    books: 'Books',
    post: "Post",
    cancel: 'Cancel',
    save: 'Save',
    setStatusAdmin: 'Set Admin Status',
    setStatusUser: 'Set User Status',
  },
};
